<?php
return [
    'booking.name' => "Nom de réservation",
    'booking.arrival_date' => "Date d'arrivée",
    'booking.departure_date' => "Date de départ",
    'booking.nights' => "Nuitées",
    'booking.phone' => "Téléphone",
    'booking.email' => "Email",
    'property.name' => "Nom du logement",
    'property.address' => "Adresse du logement",
    'property.owner_name' => "Nom du propriétaire",
    'property.owner_phone' => "Téléphone du propriétaire",
    'property.owner_email' => "Email du propriétaire",
    'property.beds_single' => "Nombre de lits simples",
    'property.beds_double' => "Nombre de lits doubles",
    'property.bathrooms' => "Nombre de salles de bain",
    'property.capacity' => "Capacité maximum",
    'property.surface' => "Surface",
    'property.custom_fields' => "Champs personnalisés",
];